export const metadata: Metadata = {
  title: "Article Page",
  description: "Article Page Generated by next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  )
}